# Generated by Django 4.0.6 on 2024-03-2010:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0005_rename_pet_review_pet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='pet.pet'),
        ),
    ]
