# Generated by Django 4.0.6 on 2023-01-18 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='leave_comment',
            field=models.CharField(default='address', max_length=300),
        ),
        migrations.AddField(
            model_name='activity',
            name='multiple_choice',
            field=models.CharField(choices=[('activity-placed', 'activity-placed'), ('on-transit', 'on-transit'), ('activity-cancelled', 'activity-cancelled'), ('activity-delivered', 'activity-delivered')], default='paypal', max_length=50),
        ),
    ]
