# Generated by Django 4.0.6 on 2023-01-18 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0002_activity_leave_comment_activity_multiple_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='multiple_choice',
            field=models.CharField(choices=[('activity-placed', 'activity-placed'), ('on-transit', 'on-transit'), ('activity-cancelled', 'activity-cancelled'), ('activity-delivered', 'activity-delivered')], default='Pal', max_length=50),
        ),
    ]
