# Generated by Django 4.0.6 on 2024-03-25 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0002_activity_billing_address_activity_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='payment_method',
            field=models.CharField(choices=[('activity-placed', 'activity-placed'), ('on-transit', 'on-transit'), ('activity-cancelled', 'activity-cancelled'), ('activity-delivered', 'activity-delivered')], default='Paypal', max_length=50),
        ),
    ]
