# Generated by Django 4.0.6 on 2023-01-18 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0003_alter_activity_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='payment_method',
            field=models.CharField(choices=[('activity-placed', 'activity-placed'), ('on-transit', 'on-transit'), ('activity-cancelled', 'activity-cancelled'), ('activity-delivered', 'activity-delivered')], max_length=50),
        ),
    ]
